spring:
  datasource:
    url: jdbc:mysql://localhost:3306/estudos_java
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem

server:
  error:
    include-stacktrace: never

api:
  name: 'API JavaEstudos'
  security:
    token:
      secret: ${JWT_SECRET:1234567890}